version: '3.9'

services:
  user-control-api:
    build: .
    image: ml-hub-user-control:latest
    environment:
      - USER=mlhub
      - PASSWORD=m5F62*V
    depends_on:
      - mariadb
    ports:
      - 5050:8080
    restart: always

  mariadb:
    image: mariadb:10.7.8
    environment:
      - MARIADB_ROOT_PASSWORD=rI423^pWJg9y
      - MARIADB_DATABASE=Users
      - MARIADB_USER=mlhub
      - MARIADB_PASSWORD=m5F62*V
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 9000:3306
