version: '3.9'

services:
  api:
    build: .
    image: ml-hub-user-control:latest
    environment:
      - USER=mlhub
      - PASSWORD=m5F62*V
    depends_on:
      - mariadb
    ports:
      - 5050:80

  mariadb:
    image: mariadb:10.7.8
    environment:
      - MARIADB_ROOT_PASSWORD=rI423^pWJg9y
      - MARIADB_DATABASE=users
      - MARIADB_USER=mlhub
      - MARIADB_PASSWORD=m5F62*V
    volumes:
      - mariadb-data:/mariadb-data/
